{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "txlab.fullname" . }}-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "txlab.fullname" . }}-kafka
  template:
    metadata:
      labels:
        app: {{ include "txlab.fullname" . }}-kafka
    spec:
      containers:
        - name: redpanda
          image: {{ .Values.kafka.image }}
          args: ["redpanda", "start", "--smp", "1", "--memory", "1G", "--reserve-memory", "0M", "--overprovisioned", "--node-id", "0", "--check=false"]
          ports:
            - containerPort: 9092
              name: kafka
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://{{ include "txlab.fullname" . }}-kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "txlab.fullname" . }}-kafka
spec:
  ports:
    - port: 9092
      targetPort: kafka
      name: kafka
  selector:
    app: {{ include "txlab.fullname" . }}-kafka
{{- end }}
